# actuator 的相关配置, 如 management.endpoints.web.exposure.include 定义那些接口可以使用
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: pro-ariadne
server:
#  port: ${random.int[10000,19999]}
  port: 2020
