# ${random.int[10000,19999]}
# actuator 的相关配置, 如 management.endpoints.web.exposure.include 定义那些接口可以使用
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: server-aa
server:
  port: 4002

demo:
  my:
    id: server-aa-1
  serverAB:
    name: server-ab
  serverAC:
    name: server-ac


