# ${random.int[10000,19999]}
# actuator 的相关配置, 如 management.endpoints.web.exposure.include 定义那些接口可以使用
management:
  endpoints:
    web:
      exposure:
        include: '*'

# spring boot 配置
# spring.application.name 会作为服务实例的名称
# 设置了 tomcat 处理并发请求的个数, 模拟局限性以测试 ab 服务的 hystrix
spring:
  application:
    name: server-ac
server:
  port: 4201
  tomcat:
    accept-count: 6
    max-connections: 6
    max-threads: 6

demo:
  my:
    id: server-ac-1

